import Head from "next/head";
import { ThemeProvider } from "./theme/theme-provider";
import ThemeSwitch from "./theme/theme-switch";
import { NavigationMenuDemo } from "./navigation/main-navigation";

export default function Layout({ children }) {
  return (
    <>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="m-auto flex flex-row justify-between pt-12 sm:w-[400px] md:w-[700px] lg:w-[1024px]">
          <NavigationMenuDemo />
          <ThemeSwitch />
        </div>
        <main className="flex min-h-screen flex-col items-center justify-center gap-8">
          {children}
        </main>
      </ThemeProvider>
    </>
  );
}
